### ISSUE TITLE
doesn't trigger snippet

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc-emmet#1]
test.js

```javascript
div>li   // can't work
div>li*3  // can work
```

record: https://asciinema.org/a/4MOWvNTG9dCBLH7R0ZrOfc11K

**Comment by chemzqm** [comment]
I can't reproduce the problem, consider debug it: https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by iamcco** [comment]
ok, will do it later

**Comment by cjnucette** [comment]
Hi, I'm using the __Example vim configuration__ in <https://github.com/neoclide/coc.nvim>, and everything is working as expected, so it's probably a configuration issue.
