### ISSUE TITLE
补全

### ISSUE THREAD

**Issue by SlippyJimmy** [neoclide/coc-emmet#13]
请问默认的补全触发键是什么？

**Comment by chemzqm** [comment]
看 coc.nvim 的 wiki

**Comment by ejkgmea** [comment]
> 

make srue you have installed `emmet.vim `plugin in your vim editor and then you can set ` let g:user_emmet_leader_key = "," `in your vimrc or `vim.g.user_emmet_leader_key = "," ` in your init.lua which means you can tapping `<leader> , ` to activate emmet
