### ISSUE TITLE
Sibling: '+' operator in css file is weird ? emmet completion triggerd occasionally.

### ISSUE THREAD

**Issue by eki3z** [neoclide/coc-emmet#14]
just as @onlurking mentiond  in #3 , I can't trigger the completion with nested Abbreviations in css file,

![notrigger](https://user-images.githubusercontent.com/35212403/71203565-2c9dad00-22d9-11ea-9b7e-f7528ce3f9c0.gif)

but whatever you nested ahead, you add something like m10p, p4 which has numeric value as ending, emmet completion always succeed.

![trigger](https://user-images.githubusercontent.com/35212403/71203574-30c9ca80-22d9-11ea-817c-89ea79077d30.gif)

Not only in coc-emmet, I try this in vscode and it's the same , coc has a extra bug that it can't complete  '!' as the '!important'. 
Anyway, without nested , single abbr in css  is enough for me. This is my emmet settings:

```
  // emmet
  "emmet.showExpandedAbbreviation": "always",
  "emmet.priority": 99,
```

nvim version :0.4.3

**Comment by Vitruvius21** [comment]
@liuyinz any solution for this? I have the same problem
