### ISSUE TITLE
How can I use emmet

### ISSUE THREAD

**Issue by vinibispo** [neoclide/coc-emmet#19]
Hello everyone, I know you're tired seeing my issues, but I'm trying hard to use emmet in vue, but no way. I know that question looks like a silly question, but you'll make my day if you answer that. I'll send my coc-settings.json

**Comment by vinibispo** [comment]
``{
  "vetur.trace.server": "verbose",                                                  
  "vetur.useWorkspaceDependencies": true,
  "vetur.completion.autoImport": true,
  "vetur.completion.useScaffoldSnippets": true,
  "vetur.completion.tagCasing": "kebab",
 "vetur.validation.template": true,
 "vetur.validation.style": true,
 "vetur.format.enable": true,
 "emmet.showAbbreviationSuggestions": true,
 "vetur.format.defaultFormatter.js": "vscode-typescript",
 "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "vue",
    "json"
  ],  
  "emmet.includeLanguages": {                                                       
    "vue-html": "html",
    "jsx": "javascript-react"
  },  
  "emmet.showSuggestionsAsSnippets": true,
  "emmet.showExpandedAbbreviation": "always",
  "snippets.loadFromExtensions": true
}
``

**Comment by vinibispo** [comment]
Please answer, what am I doing wrong?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-emmet/blob/master/Readme.md#options

**Comment by chemzqm** [comment]
You should use https://github.com/mattn/emmet-vim, this extension provide completion support only.

**Comment by vinibispo** [comment]
Ok, thank you, sorry for bothering you

**Comment by vinibispo** [comment]
It's working, thank you so much, you made my day

**Comment by shashinvision** [comment]
> You should use https://github.com/mattn/emmet-vim, this extension provide completion support only.

Work for me, thanks :D
