### ISSUE TITLE
Support for multi type Vue file

### ISSUE THREAD

**Issue by ghost** [neoclide/coc-emmet#21]
Is it possible to make `coc-emmet` work for `template` (for `http`abbreviations) and `style` (for `css` abbreviations) sections of Vue files (and no abbreviations for `script` section at all)?

At the moment I can get following setups:
* with `"emmet.includeLanguages": { "vue-html": "html" }` there is no expansion happening in Vue file (`vue` filetype) at all
* with `"emmet.includeLanguages": { "vue": "html" }` I get `html` only expansions working in all three sections (`template`, `script`, `style`). No `css` expansions in `style` section though, only `html` expansions.

**Comment by chemzqm** [comment]
No

**Comment by fovj** [comment]
Use `"emmet.includeLanguages": { "vue": "css" }`, It Works.
And the html part always work.

**Comment by ghost** [comment]
@singlexyz Perfect, works very nicely. Wish there was a way to disable it for script section though.
