### ISSUE TITLE
emmet snippet clobbers TSC completions

### ISSUE THREAD

**Issue by unphased** [neoclide/coc-emmet#23]
When I am writing code using tsserver (managed by coc-tsserver extension) and emmet (coc-emmet), if the emmet extension is enabled, it tends to overpower tsserver output. I'd like to understand if this is expected behavior or a bug. 

For example, I have in the context a variable named `p`. If I type `p.` in the buffer, I am usually hoping to see a list of semantic completions for props on the type of p. However, for whatever reason the `p.` emmet completion snippet (`<p className="">|</p>`) is the only option provided to me. 

If I manually switch the emmet extension off using `cocList`, the TSC behavior is correct and desired. Curiously, using this method to re-enable emmet appears to not work, I have to restart nvim to get it to start producing emmet completions again. This one must be a bug, but I'm hoping to find a resolution so that this bug won't be an issue.

This is not just an edge case, by the way. Due to emmet's terse nature, many code-like prefixes will trigger emmet when undesired. 

If I type `groups[0].`, also hoping to get a list of TSC completion suggestions, which it would deliver if emmet was disabled, I get this snippet suggestion: `<group 0="|" className="">|</group>`. Such a desperate suggestion, emmet. I get that it's just doing its job though. 

I really like emmet's functionality for when I'm writing HTML and I never want to use it when I'm not writing HTML. So, I have to get to the bottom of why it is clobbering other extensions' suggestions, otherwise I'll have to fully disable it, which is a shame, because implementing emmet with snippets is really neat. Thank you.

**Comment by unphased** [comment]
note... I just discovered mention of a coc feature called "preselect", it may be possible that this feature has something to do with this. Searching for documentation on what that is now. 

Update: Looks like disabling preselect did nothing to change this behavior.

**Comment by chemzqm** [comment]
Fixed by edeb4c2

**Comment by unphased** [comment]
Thank you. I can confirm that after I performed a temporary code update by running `npm i git://github.com/neoclide/coc-emmet#master` inside of `~/.config/coc/extensions/` that this works perfectly. I noticed the commit dates 3 days farther back from my issue, i guess it was pretty good timing. Thank you for taking emmet in vim to the next level. Cheers!
