### ISSUE TITLE
Seeking information on emmet.priority setting

### ISSUE THREAD

**Issue by homogulosus** [neoclide/coc-emmet#24]
Hi. First of all thanks for the really good job on Coc and all the plugins. 

I am looking information on emmet.priority setting to understand better how if works or if it works at all. Yesterday I had an issue with htmldjango and emmet.includeLanguages: {"htmldjango": "html'} solved the issue for me. But I came across emmet.priority setting  thinking it could be useful too but I  don't really understand its behaviour and package.json does not have description for such setting. Could anyone explain ? thanks in advance.

**Comment by chemzqm** [comment]
It's priority of completion source.
