### ISSUE TITLE
Custom snippets not available in autocomplete

### ISSUE THREAD

**Issue by lightcap** [neoclide/coc-emmet#28]
Custom snippets don't show up in the suggestions when following the README at [mattn/emmet-vim](https://github.com/mattn/emmet-vim/blob/master/README.mkd) to add them to emmet-vim.

`let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.snippets_custom.json')), "\n"))`

They'll work fine with the emmet keystrokes, but not Coc. Is this intended?

![projec corporate-web) - NVIM 2020-08-25 15-02-34](https://user-images.githubusercontent.com/12123/91232460-050ea800-e6e4-11ea-8975-7de9dab3c541.png)

**Comment by chemzqm** [comment]
It is expected, since coc-emmet can't load snippets from emmet-vim.
Maybe emmet-vim could expose a function that could provide snippets.
