### ISSUE TITLE
Several CSS expansions at once

### ISSUE THREAD

**Issue by onlurking** [neoclide/coc-emmet#3]
In Sublime and VS Code i write the following emmet shorthand for CSS:
```
aic+df+fxdc+jcc
```
which turns into:
```css
  align-items: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
```

Using `+` to write several expansions doesn't work in coc-emmet.

**Comment by chemzqm** [comment]
It's not feature of coc-emmet, it does completion only, try https://github.com/mattn/emmet-vim
