### ISSUE TITLE
Pug not supported by default? 

### ISSUE THREAD

**Issue by raulbonifacio** [neoclide/coc-emmet#30]
Hi! First of all, thank you for developing the extension!

I've noticed something strange. Even though it's a fork from the vscode-emmet, the 
`emmet.includeLanguages` seems to not work properly when I'm working with `.pug` files.

I have to map **pug** filetypes to **jade** for it to work. I don't know if this is the way it should be.
I thought pug files were supported by default. Maybe I'm doing something wrong...

This doesn't work. 
![image](https://user-images.githubusercontent.com/42476919/99998790-f779c480-2d9d-11eb-9871-b9392e7f0da4.png)

This is how I'm using it.
![image](https://user-images.githubusercontent.com/42476919/99998664-cbf6da00-2d9d-11eb-87f5-2303c91acf45.png)

Setting the _filetype_ doesn't work either.

**Comment by chemzqm** [comment]
Yes, the filetype should be jade, checkout `:h g:coc_filetype_map`
