### ISSUE TITLE
Emmet is showing recommendations but not completing!

### ISSUE THREAD

**Issue by BrianZhang1** [neoclide/coc-emmet#32]
I just installed emmet using :CocInstall coc-emmet and I was having some trouble using it. When using the shortcuts, the options show up alright, as shown in this picture:
https://imgur.com/a/Fowlc46 
The problem is, there is no way to actually use the option. Pressing tab simply cycles through the options, while Space or Enter just makes a Space/Enter instead of creating the ul>li shown. Is there some configuration in :CocConfig I'm missing, or what's going on?
I'm happy to give any additional info.

**Comment by BrianZhang1** [comment]
I didn't realize emmet needed a different key for completing the command.

**Comment by babolinGiordano** [comment]
Hello, 
i have the same problem. 
Could show me what option I need to set to select one?
Thanks

**Comment by BrianZhang1** [comment]
@babolinGiordano I think it is ctrl-y to autocomplete. I don't exactly remember though, since I haven't used it in awhile. TAB to swap between options and CTRL-Y autocomplete is what I remember.

**Comment by dmshvetsov** [comment]
`<C-n>` and `<C-p>` to pick an option to expand and `<C-y>` to expand chosen option.
