### ISSUE TITLE
Use with Styled Components Library

### ISSUE THREAD

**Issue by joshmedeski** [neoclide/coc-emmet#34]
How do I set up this plugin to work with [styled-components](https://styled-components.com/)?

I want CSS rules to work inside a styled component on a `jsx`/`tsx` file.

**Comment by chemzqm** [comment]
Out of scope.

**Comment by joshmedeski** [comment]
Bummer, if anyone finds this in the future and wants to build a solution, feel free to reach out to me and I may be able to help.

**Comment by chemzqm** [comment]
There is https://github.com/fannheyward/coc-styled-components, although I don't use it but seems nice.
