### ISSUE TITLE
! and !!! autocompleted, but never expanded

### ISSUE THREAD

**Issue by benyaminl** [neoclide/coc-emmet#47]
Hello, I have encounter bug, when I use ! and !!!, it do show autocompletation, but it won't autocomplete. The rest of emmet runs fine, like doc or div even with some variable. 

Is there anyway to know what cause it? Thank you

**Comment by moskalenko2k24** [comment]
Have same issue, use Fedora 35, Vim 8.2.

**Comment by moniquelive** [comment]
The snippet `html:5` worked for me btw

**Comment by moskalenko2k24** [comment]
@moniquelive it realy works, thank you! It's much more simpler to remember html:5 than writing it manually.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
