### ISSUE TITLE
Emmet not triggering in SCSS files

### ISSUE THREAD

**Issue by ceuk** [neoclide/coc-emmet#6]
Feel like I may be being a bit dumb here, but I've tried: 
`"emmet.includeLanguages": {"scss": "css", "sass": "css"}` 
and it doesn't seem to help. Works fine in CSS files

**Comment by hansemschnokeloch** [comment]
Maybe that the filetype for scss files isn't scss with your vim configuration.
I had this issue with twig files.
Open a scss file and enter the command
`:set filetype?`
that will give you the actual filetype of scss files

**Comment by chemzqm** [comment]
Use `:echo &filetype` to checkout your filetype.

**Comment by ahmedelgabri** [comment]
I have the same issue with files like this `foo.html.twig`

`:echo &ft` gives `html.twig` and I added that but it doesn't work, that's what I have now & still doesn't work…

```json5
"emmet.includeLanguages": {"html.twig": "html", "twig": "html", "*.twig": "html"},
```

**Comment by chemzqm** [comment]
Checkout `:h g:coc_filetype_map`

**Comment by ahmedelgabri** [comment]
That worked, thanks @chemzqm
