### ISSUE TITLE
如何设置在filetype在.tsx, .jsx, .js 中也生效

### ISSUE THREAD

**Issue by DemonCloud** [neoclide/coc-emmet#7]
"emmet.includeLanguages": {
    "vue-html": "html",
    "cubec": "html",
    "template": "html",
    "handlebars": "html",
    "mustache": "html",
    "javascript": "javascriptreact",
    "typescript": "typescriptreact",
    "javascript.jsx": "javascriptreact",
    "typescript.tsx": "typescriptreact"
  }

这样配置有问题么 ？或者说怎样设置

**Comment by arrudaricardo** [comment]
I'm having similar problem, not been able to include emmet for erb files. 
```  
  "emmet.includeLanguages": {"erb":"html", "html.erb":"html", "*.erb":"html", "ruby":"html"},
    "emmet.showExpandedAbbreviation": "always",
    "emmet.showSuggestionsAsSnippets": true
```

**Comment by opchaves** [comment]
I was able to get emmet working in `.erb` files by using the language name `eruby`

```json
"emmet.includeLanguages": {
  "eruby": "html",
},
```

**Comment by DemonCloud** [comment]
可以了，你们已经修复了
