### ISSUE TITLE
Go to next/previous edit points

### ISSUE THREAD

**Issue by igorlakic** [neoclide/coc-emmet#8]
I would like to know if it's currently possible to go to next/previous edit points? One example would be:  `<source src="" type="">` and you want to go from one to another edit point (""). I've been trying to find if any keybinding for that exist but without success.

Thanks in advance!

**Comment by igorlakic** [comment]
I figured it out. you can do that with: 
`<Ctrl>j` and `<Ctrl>k`  jump to next/previous placeholder, it's default of coc.nvim.

**Comment by ghost** [comment]
LMAO, i was looking for the same thing
